[project]
name = "llm-int"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm>=1.77.7",
    "marimo[mcp]>=0.16.5",
    "openai>=2.2.0",
]
